name: Transfer to gitlab.dustinrue.com

on:
  push:
    branches:
      - 'chore/gitlab-test'

jobs:
  Transfer_to_gitlab:
    environment:
      name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run script file
        run: |
          mkdir -p ${HOME}/.ssh
          chmod 0700 ${HOME}/.ssh
          ls -lh ${HOME}/.ssh
          ssh-keyscan gitlab.dustinrue.com > ${HOME}/.ssh/known_hosts
          echo ${{ secrets.GITLAB_SSH_PRIVATE_KEY }} > ${HOME}/.ssh/id_rsa
          chmod 0600 ${HOME}/.ssh/id_rsa
          chmod 0600 ${HOME}/.ssh/known_hosts
          ls -lh ${HOME}/.ssh
          cat ${HOME}/.ssh/known_hosts


        shell: bash

